services:
  - type: web
    name: sea-dashboard
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PRODUCTION
        value: "true"

databases:
  - name: sea-db
    databaseName: sea
    plan: free
